module.exports = {
  docs: [
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: ['components'],
    },
    {
      type: 'category',
      label: 'Action Sheet',
      collapsed: false,
      items: ['action-sheet'],
    },
    {
      type: 'category',
      label: 'Accordion',
      collapsed: false,
      items: ['accordion', 'accordion-group'],
    },
    {
      type: 'category',
      label: 'Alert',
      collapsed: false,
      items: ['alert'],
    },
    {
      type: 'category',
      label: 'Badge',
      collapsed: false,
      items: ['badge'],
    },
    {
      type: 'category',
      label: 'Breadcrumb',
      collapsed: false,
      items: ['breadcrumb', 'breadcrumbs'],
    },
    {
      type: 'category',
      label: 'Button',
      collapsed: false,
      items: ['button', 'ripple-effect'],
    },
    {
      type: 'category',
      label: 'Card',
      collapsed: false,
      items: ['card', 'card-content', 'card-header', 'card-subtitle', 'card-title'],
    },
    {
      type: 'category',
      label: 'Checkbox',
      collapsed: false,
      items: ['checkbox'],
    },
    {
      type: 'category',
      label: 'Chip',
      collapsed: false,
      items: ['chip'],
    },
    {
      type: 'category',
      label: 'Content',
      collapsed: false,
      items: ['app', 'content'],
    },
    {
      type: 'category',
      label: 'Date & Time Pickers',
      collapsed: false,
      items: ['datetime', 'datetime-button', 'picker'],
    },
    {
      type: 'category',
      label: 'Floating Action Button',
      collapsed: false,
      items: ['fab', 'fab-button', 'fab-list'],
    },
    {
      type: 'category',
      label: 'Grid',
      collapsed: false,
      items: ['grid', 'col', 'row'],
    },
    {
      type: 'category',
      label: 'Infinite Scroll',
      collapsed: false,
      items: ['infinite-scroll', 'infinite-scroll-content'],
    },
    {
      type: 'category',
      label: 'Icons',
      collapsed: false,
      items: ['icon'],
    },
    {
      type: 'category',
      label: 'Input',
      collapsed: false,
      items: ['input', 'textarea'],
    },
    {
      type: 'category',
      label: 'Item',
      collapsed: false,
      items: ['item', 'item-divider', 'item-group', 'item-sliding', 'item-options', 'item-option', 'label', 'note'],
    },
    {
      type: 'category',
      label: 'List',
      collapsed: false,
      items: ['list', 'list-header'],
    },
    {
      type: 'category',
      label: 'Media',
      collapsed: false,
      items: ['avatar', 'icon', 'img', 'thumbnail'],
    },
    {
      type: 'category',
      label: 'Menu',
      collapsed: false,
      items: ['menu', 'menu-button', 'menu-toggle', 'split-pane'],
    },
    {
      type: 'category',
      label: 'Modal',
      collapsed: false,
      items: ['modal', 'backdrop'],
    },
    {
      type: 'category',
      label: 'Navigation',
      collapsed: false,
      items: ['nav', 'nav-link'],
    },
    {
      type: 'category',
      label: 'Popover',
      collapsed: false,
      items: ['popover'],
    },
    {
      type: 'category',
      label: 'Progress Indicators',
      collapsed: false,
      items: ['loading', 'progress-bar', 'skeleton-text', 'spinner'],
    },
    {
      type: 'category',
      label: 'Radio',
      collapsed: false,
      items: ['radio', 'radio-group'],
    },
    {
      type: 'category',
      label: 'Range',
      collapsed: false,
      items: ['range'],
    },
    {
      type: 'category',
      label: 'Refresher',
      collapsed: false,
      items: ['refresher', 'refresher-content'],
    },
    {
      type: 'category',
      label: 'Reorder',
      collapsed: false,
      items: ['reorder', 'reorder-group'],
    },
    {
      type: 'category',
      label: 'Routing',
      collapsed: false,
      items: ['router', 'router-link', 'router-outlet', 'route', 'route-redirect'],
    },
    {
      type: 'category',
      label: 'Searchbar',
      collapsed: false,
      items: ['searchbar'],
    },
    {
      type: 'category',
      label: 'Segment',
      collapsed: false,
      items: ['segment', 'segment-button'],
    },
    {
      type: 'category',
      label: 'Select',
      collapsed: false,
      items: ['select', 'select-option'],
    },
    {
      type: 'category',
      label: 'Tabs',
      collapsed: false,
      items: ['tabs', 'tab', 'tab-bar', 'tab-button'],
    },
    {
      type: 'category',
      label: 'Toast',
      collapsed: false,
      items: ['toast'],
    },
    {
      type: 'category',
      label: 'Toggle',
      collapsed: false,
      items: ['toggle'],
    },
    {
      type: 'category',
      label: 'Toolbar',
      collapsed: false,
      items: ['toolbar', 'header', 'footer', 'title', 'buttons', 'back-button'],
    },
    {
      type: 'category',
      label: 'Typography',
      collapsed: false,
      items: ['text'],
    },
    {
      type: 'category',
      label: 'Resources',
      collapsed: false,
      items: ['api'],
    },
  ],
};
